name: Push to GCR GitHub Action
on:
  workflow_call:
    inputs:
      context:
        description: The path to the docker context in the repository
        required: false
        default: "."
        type: string
      file:
        description: The path to the Dockerfile in the repository
        required: false
        default: "./Dockerfile"
        type: string
      tags:
        description: The image tags to push
        required: true
        type: string
    secrets:
      GCLOUD_SERVICE_ACCOUNT:
        description: Service account email with push access to GCR
        required: true
      GCLOUD_SERVICE_KEY:
        description: Service account JSON with push access to GCR
        required: true

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v0
        with:
          service_account: "${{ secrets.GCLOUD_SERVICE_ACCOUNT }}"
          credentials_json: "${{ secrets.GCLOUD_SERVICE_KEY }}"
      - uses: google-github-actions/setup-gcloud@v0
      - name: authenticate to GCR
        run: gcloud auth configure-docker
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "${{ inputs.context }}"
          file: "${{ inputs.file }}"
          push: true
          tags: "${{ inputs.tags }}"
