name: Run tests on npm app
on:
  workflow_call:
    inputs:
      nodeVersion:
        description: The version of node to use
        default: "16"
        type: string
    secrets:
      SLACK_NOTIFICATIONS_BOT_TOKEN:
        description: Bot token for Slack notifications
        required: true

jobs:
  run-npm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack started
        if: success()
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: github-actions
          status: STARTED
          color: warning
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ inputs.nodeVersion }}"
      - name: install npm packages
        run: npm ci
      - name: run npm tests
        run: npm test
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-actions
          status: SUCCESS
          color: good
      - name: Notify slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-actions
          status: FAILED
          color: danger
