name: Build and publish npm container image
on:
  workflow_call:
    inputs:
      lfs:
        description: Use Git LFS when checkout out files
        default: false
        type: boolean
      nodeVersion:
        description: The version of node to use
        default: "lts/*"
        type: string
      context:
        description: The path to the docker context in the repository
        required: false
        default: "."
        type: string
      file:
        description: The path to the Dockerfile in the repository
        required: false
        default: "./Dockerfile"
        type: string
      ecrRepository:
        description: The ECR image repository to push to
        required: false
        default: ""
        type: string
      gcrRepository:
        description: The GCR image repository to push to
        required: false
        default: ""
        type: string
      aws_region:
        description: The region for the ECR repo
        required: false
        default: us-east-1
        type: string
      legacyPeerDeps:
        description: Use --legacy-peer-deps flag with npm ci
        required: false
        default: false
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        description: AWS key with push access to ECR
        required: false
      AWS_SECRET_ACCESS_KEY:
        description: AWS secret with push access to ECR
        required: false
      GCLOUD_SERVICE_ACCOUNT:
        description: Service account email with push access to GCR
        required: false
      GCLOUD_SERVICE_KEY:
        description: Service account JSON with push access to GCR
        required: false
      SLACK_NOTIFICATIONS_BOT_TOKEN:
        description: Bot token for Slack notifications
        required: true

jobs:
  npm-build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack started
        if: success()
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: zuplo/github-action-slack-notify-build@v2
        with:
          channel: github-actions
          status: STARTED
          color: warning
      - uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.lfs }}
      - name: Get the ref name
        id: get_ref_name
        run: |
          if [ ! -z "$GITHUB_REF_NAME" ]
          then
              GITHUB_REF_TMP=${GITHUB_REF_NAME}
          else
              GITHUB_REF_TMP=${GITHUB_REF#refs/heads/}
              GITHUB_REF_TMP=${GITHUB_REF_TMP#refs/tags/}
          fi

          GITHUB_REF_CLEANED=${GITHUB_REF_TMP//\//-}
          echo "GIT_REF_NAME=${GITHUB_REF_TMP}" >> $GITHUB_OUTPUT
          echo "GIT_REF_DOCKER_TAG=${GITHUB_REF_CLEANED}" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ inputs.nodeVersion }}"
      - name: install npm packages
        run: npm ci${{ inputs.legacyPeerDeps && ' --legacy-peer-deps' || '' }}
      - name: run npm tests
        run: npm test
      - name: build repository
        run: npm run build
      # Google
      - uses: google-github-actions/auth@v1
        if: "${{ inputs.gcrRepository != '' }}"
        with:
          service_account: "${{ secrets.GCLOUD_SERVICE_ACCOUNT }}"
          credentials_json: "${{ secrets.GCLOUD_SERVICE_KEY }}"
      - uses: google-github-actions/setup-gcloud@v1
      - name: authenticate to GCR
        if: "${{ inputs.gcrRepository != '' }}"
        run: gcloud auth configure-docker
      # Amazon
      - name: Configure AWS credentials
        if: "${{ inputs.ecrRepository != '' }}"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}
      - name: Login to Amazon ECR
        if: "${{ inputs.ecrRepository != '' }}"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      # BEGIN BUILD
      - name: Build and push images to ECR
        if: "${{ inputs.ecrRepository != '' }}"
        uses: docker/build-push-action@v4
        with:
          context: "${{ inputs.context }}"
          file: "${{ inputs.file }}"
          push: true
          tags: ${{ inputs.ecrRepository }}:${{ steps.get_ref_name.outputs.GIT_REF_DOCKER_TAG }}
      - name: Build and push images to GCR
        if: "${{ inputs.gcrRepository != '' }}"
        uses: docker/build-push-action@v4
        with:
          context: "${{ inputs.context }}"
          file: "${{ inputs.file }}"
          push: true
          tags: ${{ inputs.gcrRepository }}:${{ steps.get_ref_name.outputs.GIT_REF_DOCKER_TAG }}
      # END BUILD
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: zuplo/github-action-slack-notify-build@v2
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-actions
          status: SUCCESS
          color: good
      - name: Notify slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: zuplo/github-action-slack-notify-build@v2
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-actions
          status: FAILED
          color: danger
