name: Run tests on npm app
on:
  workflow_call:
    inputs:
      lfs:
        description: Use Git LFS when checkout out files
        default: false
        type: boolean
      nodeVersion:
        description: The version of node to use
        default: "lts/*"
        type: string
      legacyPeerDeps:
        description: Use --legacy-peer-deps flag with npm ci
        required: false
        default: false
        type: boolean
    secrets:
      SLACK_NOTIFICATIONS_BOT_TOKEN:
        description: Bot token for Slack notifications
        required: true

jobs:
  run-npm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack started
        if: success()
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: zuplo/github-action-slack-notify-build@v2
        with:
          channel: github-actions
          status: STARTED
          color: warning
      - uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.lfs }}
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ inputs.nodeVersion }}"
      - name: install npm packages
        run: npm ci${{ inputs.legacyPeerDeps && ' --legacy-peer-deps' || '' }}  
      - name: run npm tests
        run: npm test
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: zuplo/github-action-slack-notify-build@v2
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-actions
          status: SUCCESS
          color: good
      - name: Notify slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: zuplo/github-action-slack-notify-build@v2
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-actions
          status: FAILED
          color: danger
